# Generated by Django 4.1.2 on 2022-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_posts_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
