# Generated by Django 4.1.2 on 2022-10-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_posts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
