# Generated by Django 4.1.2 on 2022-11-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_posts_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('certificate', models.FileField(upload_to='Certificate/')),
            ],
        ),
    ]
